language: ruby
rvm:
  - 2.1.2
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rake db:reset RAILS_ENV=test
  - bundle exec cucumber
  - bundle exec rspec spec/