
development:
  adapter: mysql2
  encoding: utf8 
  database: fileserver-dev
  pool: 10 
  username: root 
  password:  
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true

test: &test
  adapter: mysql2
  encoding: utf8 
  database: fileserver-test
  pool: 10 
  username: root 
  password:  
  socket: /var/run/mysqld/mysqld.sock 
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8 
  database: fileserver-production
  pool: 10 
  username: root 
  password:  
  socket: /var/run/mysqld/mysqld.sock 
  reconnect: true

cucumber:
  <<: *test